/// <reference types="cypress" />

describe('test-filtering', () => {
    beforeEach(() => {
        cy.visit('http://localhost:5173')
    })

    it('should display all items', () => {
        cy.visit('http://localhost:5173/clients/')
        cy.get('#viewBtn').click()
        cy.get('#editarDadosPessoais').click()
        cy.get('#email').clear()
        cy.get('#email').type('marcos@mail.com')
        cy.get('#salvarDadosPessoaisBtn').click()
        cy.get('#dadosEndereco').click()
        cy.get('#editarEndereco').click()
        cy.get('#logradouro').clear()
        cy.get('#logradouro').type('R Araçatuba')
        cy.get('#apelidoEndereco').clear()
        cy.get('#apelidoEndereco').type('Casa 516')
        cy.get('#cobranca').click()
        cy.get('#salvarEnderecoBtn').click()
        cy.get('#addEnderecoBtn').click()
        cy.get('#cep').type('08710165')
        cy.get('#tipoLog').click()
        cy.get('#tipoLog_1').click()
        cy.get('body').click(0, 0)
        cy.get('#tipoRes').click()
        cy.get('#tipoRes_1').click()
        cy.get("body").click({ force: true, x: 0, y: Cypress.$(window).height() })
        cy.get('#numero').type('509')
        cy.get('#pais').type('Brasil')
        cy.get('#apelidoEnd').type('Mogi Avenida')
        cy.get('#salvarEnderecoBtn').click()
        cy.get('#dadosEndereco').click()
        cy.get('#dadosCartao').click()
        cy.get('#editarCartao').click()
        cy.get('#numeroCartao').clear()
        cy.get('#numeroCartao').type('1234567890123456')
        cy.get('#salvarCartaoBtn').click()
        cy.get('#addCartaoBtn').click()
        cy.get('#numeroCartao').type('7777888899991111')
        cy.get('#bandeira').click()
        cy.get('#bandeira_0').click()
        cy.get("body").click(0, 0)
        cy.get('#cvv').type('124')
        cy.get('#nomeImpresso').type('Marcos Almeida Nascimento')
        cy.get('#validade').clear()
        cy.get('#validade').type('01/2040')
        cy.get("body").click(0, 0)
        cy.get('#apelidoCartao').type('ILIMITADO')
        cy.get('#salvarCartaoBtn').click()
        cy.get('#dadosCartao').click()
        cy.get('#dadosSenha').click()
        cy.get('#senha').type('!@#123qweQ')
        cy.get('#confSenha').type('!@#123qweQ')
        cy.get('#salvarSenhaBtn').click()
        cy.get('#voltarBtn').click()
    })
})